# Generated by Django 2.2 on 2021-02-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20210220_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
